# Generated by Django 5.1.4 on 2025-01-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrgen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gen',
            name='number',
            field=models.IntegerField(),
        ),
    ]
